use crate::mutation::MutationSet;

pub struct FormatPart {
    pub text: String,
    pub mutations: MutationSet,
}

pub struct FormatSet {
    pub parts: Vec<FormatPart>,
}

pub struct FormatField {
    pub name: String,
    pub question: Option<String>,
}

pub struct FormattingSets {
    pub _name: String,
    pub fields: Vec<FormatField>,
    pub sets: Vec<FormatSet>,
}

#[derive(Debug)]
pub struct FormatFieldAnswer {
    pub name: String,
    pub answer: String,
}

impl FormatFieldAnswer {
    pub fn placeholder(&self) -> String {
        format!("{{{}}}", self.name)
    }
}

impl FormattingSets {
    pub fn check_answer_names(&self, answers: &Vec<FormatFieldAnswer>) {
        let names: Vec<String> = self.fields.iter().map(|x| x.name.to_owned()).collect();

        for answer in answers {
            if !names.contains(&answer.name) {
                crate::logging::error(&format!(
                    "invalid field name: {}. Valid names: {names:?}",
                    answer.name
                ));
                panic!()
            }
        }
    }

    // TODO: foloseste un iterator in loc de functia asta jegoasa
    pub fn generate_words(&self, answers: Vec<FormatFieldAnswer>) -> Vec<String> {
        let mut result: Vec<String> = Vec::new();

        for fmt_set in &self.sets {
            let mut final_string = String::new();

            for part in &fmt_set.parts {
                let mut p_text = part.text.to_owned();

                for answer in &answers {
                    p_text = p_text.replace(&answer.placeholder(), &answer.answer)
                }

                let mutation_result = part.mutations.perform(&p_text);

                if mutation_result.mutated_words.is_empty() {
                    continue;
                }

                // combinatorical tokens are not supported, so we only put the first result
                // we will print a warning in case the mutation set generated multiple words
                if mutation_result.mutated_words.len() > 1 {
                    crate::logging::warning(
                        "a mutation inside the formatting set generated multiple words",
                    );
                    crate::logging::warning(
                        "         mutations with combinatorical tokens are not supported in formatting sets",
                    );
                    crate::logging::warning(
                        "         we will use only the first word generated by the mutations",
                    );
                }

                final_string.push_str(&mutation_result.mutated_words[0])
            }

            result.push(final_string)
        }

        result
    }
}

impl FormatSet {
    pub fn new() -> FormatSet {
        FormatSet { parts: Vec::new() }
    }
}

#[cfg(test)]
mod tests {
    use super::{FormatSet, FormatPart, FormattingSets, FormatFieldAnswer, FormatField};
    use crate::mutation::MutationSet;

    #[test]
    fn format_generation() {
        let set = FormatSet {
            parts: vec![
                FormatPart {
                    text: "{name}".to_string(),
                    mutations: MutationSet::empty_set(),
                },
                FormatPart {
                    text: "_".to_string(),
                    mutations: MutationSet::empty_set(),
                },
                FormatPart {
                    text: "{id}".to_string(),
                    mutations: MutationSet::empty_set(),
                }
            ]
        };
        
        let format_sets = FormattingSets {
            _name: "test".to_string(),
            fields: vec![
                FormatField { name: "name".to_string(), question: None },
                FormatField { name: "id".to_string(), question: None }
            ],
            sets: vec![set],
        };
        
        let answers = vec![
            FormatFieldAnswer { name: "name".to_string(), answer: "user".to_string() },
            FormatFieldAnswer { name: "id".to_string(), answer: "123".to_string() }
        ];
        
        let words = format_sets.generate_words(answers);
        assert_eq!(words, vec!["user_123"]);
    }

    #[test]
    #[should_panic]
    fn format_invalid_field() {
        let format_sets = FormattingSets {
            _name: "test".to_string(),
            fields: vec![
                FormatField { name: "name".to_string(), question: None },
            ],
            sets: vec![],
        };
        let answers = vec![
            FormatFieldAnswer { name: "age".to_string(), answer: "20".to_string() }
        ];
        format_sets.check_answer_names(&answers);
    }
    
    #[test]
    fn mutation_in_format() {
        let set = FormatSet {
            parts: vec![
                FormatPart {
                    text: "test".to_string(),
                    mutations: MutationSet {
                        mutations: vec![crate::mutation::Mutation {
                            action: crate::mutation::Action::Reverse,
                            times: 1,
                            keep_original: false
                        }]
                    }
                }
            ]
        };
        let format_sets = FormattingSets {
            _name: "test".to_string(),
            fields: vec![],
            sets: vec![set]
        };
        let words = format_sets.generate_words(vec![]);
        assert_eq!(words, vec!["tset"]);
    }
}
