use crate::mutation::MutationSet;

pub struct FormatPart {
    pub text: String,
    pub mutations: MutationSet,
}

pub struct FormatSet {
    pub parts: Vec<FormatPart>,
}

pub struct FormatField {
    pub name: String,
    pub question: Option<String>,
}

pub struct FormattingSets {
    pub _name: String,
    pub fields: Vec<FormatField>,
    pub sets: Vec<FormatSet>,
}

#[derive(Debug)]
pub struct FormatFieldAnswer {
    pub name: String,
    pub answer: String,
}

impl FormatFieldAnswer {
    pub fn placeholder(&self) -> String {
        format!("{{{}}}", self.name)
    }
}

impl FormattingSets {
    pub fn check_answer_names(&self, answers: &Vec<FormatFieldAnswer>) {
        let names: Vec<String> = self.fields.iter().map(|x| x.name.to_owned()).collect();

        for answer in answers {
            if !names.contains(&answer.name) {
                crate::logging::error(&format!(
                    "invalid field name: {}. Valid names: {names:?}",
                    answer.name
                ));
                panic!()
            }
        }
    }

    // TODO: foloseste un iterator in loc de functia asta jegoasa
    pub fn generate_words(&self, answers: Vec<FormatFieldAnswer>) -> Vec<String> {
        let mut result: Vec<String> = Vec::new();

        for fmt_set in &self.sets {
            let mut final_string = String::new();

            for part in &fmt_set.parts {
                let mut p_text = part.text.to_owned();

                for answer in &answers {
                    p_text = p_text.replace(&answer.placeholder(), &answer.answer)
                }

                let mutation_result = part.mutations.perform(&p_text);

                if mutation_result.mutated_words.is_empty() {
                    continue;
                }

                // combinatorical tokens are not supported, so we only put the first result
                // we will print a warning in case the mutation set generated multiple words
                if mutation_result.mutated_words.len() > 1 {
                    crate::logging::warning(
                        "a mutation inside the formatting set generated multiple words",
                    );
                    crate::logging::warning(
                        "         mutations with combinatorical tokens are not supported in formatting sets",
                    );
                    crate::logging::warning(
                        "         we will use only the first word generated by the mutations",
                    );
                }

                final_string.push_str(&mutation_result.mutated_words[0])
            }

            result.push(final_string)
        }

        result
    }
}

impl FormatSet {
    pub fn new() -> FormatSet {
        FormatSet { parts: Vec::new() }
    }
}
